name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  DOTNET_VERSION: '7.0.x'
  AZURE_WEBAPP_NAME: learn-github-actions
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install Dependencies
        run: dotnet restore ./learn-github-actions.sln
        
      - name: Build
        run: dotnet build ./learn-github-actions.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./learn-github-actions.sln -c Release --no-build -o {{ env.AZURE_WEBAPP_PACKAGE_PATH }} -r linux-x64 --self-contained true /p:UseAppHost=true

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"